# Name of your blog (this will show up at the top of your page and in the RSS feed)
# name: Sample Jekyll Blog
# 
# Short description (goes below the title; it will also be used in the RSS feed)
# description: This is a sample Jekyll Blog.
# 
# Your name, as you want it to appear underneath each post and in the footer
# author: Your Name
# 
# Your email if you want it to be linked on the contact page
# author_email: you@example.com
# 
# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
# category_dir: /
# 
# Make relative links work http://stackoverflow.com/a/19173888
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# When referencing JS or CSS files, do it like this: {{site.baseurl}}/path/to/css.css – note the slash immediately following the variable (just before “path”).
# When doing permalinks or internal links, do it like this: {{site.baseurl}}{{ post.url }} – note that there is no slash between the two variables.
# Finally, if you’d like to preview your site before committing/deploying using jekyll serve, be sure to pass an empty string to the --baseurl option, so that you can view everything at localhost:4000 normally (without /project-name at the beginning):  jekyll serve --baseurl ''
baseurl: '/dtexwang.github.io'
# https://github.com/jekyll/jekyll/issues/332#issuecomment-72088429
# {% assign relative-baseurl = "" %}
# {% assign canon = page.url | append: "page.html" | split: "/" %}
# {% for item in canon offset:2 %}
  # {% assign relative-baseurl = relative-baseurl | append:"../" %}
# {% endfor %}
# {{ relative-baseurl }}
# 
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
# url: http://yourdomain.com/